django_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

import menu_app.views as menu

import profile_app.views as profile
from django_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', menu.IndexView.as_view(), name='menu'),

    path('vote/', include('vote_app.urls')),

    path('profile/view/<int:profile_id>/', profile.ProfilePageView.as_view(), name='profile_view'),

    path('account/', include('profile_app.urls')),

    path('moderation/', include('moderation_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote_app/urls.py
from django.urls import path
import vote_app.views as vote_main
import vote_app.view_vote_config_subclasses as vote_config
import vote_app.view_vote_one_subclasses as vote_one


urlpatterns = [
    path('list/', vote_main.VoteListPageView.as_view(), name='vote_list'),
    path('create/', vote_config.CreateVotingView.as_view(), name='vote_create'),
    path('edit/<int:voting_id>/', vote_config.EditVotingView.as_view(), name='vote_edit'),
    path('delete/<int:voting_id>/', vote_one.DeleteVotingView.as_view(), name='vote_delete'),
    path('view/<int:voting_id>/', vote_one.VotingView.as_view(), name='vote_view'),
]

menu_app/models.py
from django.db import models

# Create your models here.

vote_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils import timezone

from profile_app.models import AdditionUserInfo


class Votings(models.Model):
    title = models.CharField(max_length=256)
    image = models.ImageField(upload_to='voting_images/', blank=True, null=True)  # FileField()
    description = models.TextField()
    author = models.ForeignKey(to=User, on_delete=models.SET_NULL, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField(blank=True, null=True)

    ALL = 0
    VOTED = 1
    SEE_WHO_CHOICES = [
        (ALL, 'Всем'),
        (VOTED, 'Проголосовавшим'),
    ]
    result_see_who = models.IntegerField(null=True, default=0, choices=SEE_WHO_CHOICES)

    ANYTIME = 0
    BY_TIMER = 1
    SEE_WHEN_CHOICES = [
        (ANYTIME, 'В любое время'),
        (BY_TIMER, 'После окончания'),
    ]
    result_see_when = models.IntegerField(null=True, default=0, choices=SEE_WHEN_CHOICES)

    anons_can_vote = models.BooleanField(default=False)

    ONE = 0
    MANY = 1
    VOTING_TYPE = [
        (ONE, 'Один вариант'),
        (MANY, 'Много вариантов'),
    ]
    TYPE_REFS = {
        ONE: 'radio',
        MANY: 'checkbox',
    }
    type = models.IntegerField(default=0, choices=VOTING_TYPE)

    voters_count = models.IntegerField(default=0)
    votes_count = models.IntegerField(default=0)
    variants_count = models.IntegerField(default=2)

    def get_absolute_url(self):
        return reverse_lazy('vote_view', args=(self.pk, ))

    def get_result_see_who_name(self):
        for note in self.SEE_WHO_CHOICES:
            if note[0] == self.result_see_who:
                return note[1]

    def get_result_see_when_name(self):
        for note in self.SEE_WHEN_CHOICES:
            if note[0] == self.result_see_when:
                return note[1]

    def get_img_url(self):
        try:
            return self.image.url
        except ValueError:
            return ''

    def is_ended(self):
        if self.end_date is None:
            return False
        else:
            return timezone.now() >= self.end_date

    def can_see_result(self, request):
        if self.result_see_when == Votings.BY_TIMER:
            if self.result_see_who == Votings.VOTED:
                return self.is_voted(request) and self.is_ended()
            else:
                return self.is_ended()
        else:
            if self.result_see_who == Votings.VOTED:
                return self.is_voted(request)
            else:
                return True

    def is_voted(self, request):
        if request.user.is_authenticated:
            votes = Votes.objects.filter(voting=self.pk, user=request.user)
        else:
            votes = Votes.objects.filter(voting=self.pk, fingerprint=request.POST.get('fingerprint', -1))
        return len(votes) > 0

    def can_vote(self, request):
        if self.is_ended():
            return False
        elif self.is_voted(request):
            return False
        elif not request.user.is_authenticated:
            return self.anons_can_vote
        return True

    def get_reason_cant_vote(self, request):
        if self.is_ended():
            return 'Голосование закончилось'
        elif self.is_voted(request):
            return 'Вы уже голосовали'
        elif not request.user.is_authenticated and not self.anons_can_vote:
            return 'Для этого голосования необходимо авторизоваться'
        return ''

    def can_edit(self, request):
        if not request.user.is_authenticated:
            return False
        add_info = AdditionUserInfo.objects.get(user=request.user)
        return self.author == request.user or add_info.user_rights == AdditionUserInfo.ADMIN

    def update_votes_count(self):
        variants = VoteVariants.objects.filter(voting=self)
        for variant in variants:
            variant.votes_count = len(Votes.objects.filter(variant=variant))
            variant.save()
        self.votes_count = len(Votes.objects.filter(voting=self))
        self.save()

    def update_voters_count(self):
        votes = Votes.objects.filter(voting=self)
        users = []
        fingerprints = []
        for vote in votes:
            if vote.user is not None:
                users.append(vote.user)
            if vote.fingerprint is not None:
                fingerprints.append(vote.fingerprint)
        users_set = set(users)
        fingerprints_set = set(fingerprints)
        self.voters_count = len(users_set) + len(fingerprints_set)
        self.save()

    def __str__(self):
        return f'{self.title} ({self.author})'


class VoteVariants(models.Model):
    voting = models.ForeignKey(to=Votings, on_delete=models.CASCADE)
    serial_number = models.IntegerField()
    description = models.TextField()
    votes_count = models.IntegerField()

    def get_absolute_url(self):
        return reverse_lazy('vote_view', args=(self.voting.pk,))

    def __str__(self):
        return f'{self.voting}: {self.serial_number} - {self.description}'


class Votes(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.DO_NOTHING, null=True)
    fingerprint = models.CharField(null=True, max_length=256)
    voting = models.ForeignKey(to=Votings, on_delete=models.CASCADE)
    variant = models.ForeignKey(to=VoteVariants, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse_lazy('vote_view', args=(self.voting.pk,))

    def __str__(self):
        res = f'{self.vote_date:%Y-%m-%d %H:%M} - {self.voting} - '
        if self.user is not None:
            return res + f'{self.user}'
        else:
            return res + f'Аноним {self.fingerprint}'

menu_app/views.py
from menu_app.view_subclasses import TemplateViewWithMenu


class IndexView(TemplateViewWithMenu):
    template_name = 'index.html'

menu_app/templates/bases/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/x-icon" href="{% get_media_prefix %}favicon.ico">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/btn_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/checkbox_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/radio_style.css' %}">
    {% block head %}
    {% endblock %}
</head>
<body>
    <header>
        {% include 'bases/menu.html' %}
        {% block header %}
        {% endblock %}
    </header>
    <main class="main-content">
        {% block main %}
        {% endblock %}
    </main>
    <footer>
        {% block footer %}
        {% endblock %}
        {% include 'bases/footer.html' %}
    </footer>
    <script src="https://kit.fontawesome.com/7028e958f2.js" crossorigin="anonymous"></script>
</body>
</html>

menu_app/templates/bases/checkbox_animation.html
<svg viewBox="0 0 21 21">
    <path d="M5,10.75 L8.5,14.25 L19.4,2.3 C18.8333333,1.43333333 18.0333333,1 17,1 L4,1 C2.35,1 1,2.35 1,4 L1,17 C1,18.65 2.35,20 4,20 L17,20 C18.65,20 20,18.65 20,17 L20,7.99769186"></path>
</svg>

menu_app/templates/bases/fingerprint.html
<input type="hidden" readonly name="fingerprint" id="id_fingerprint">
<script>
    function initFingerprintJS() {
        FingerprintJS.load().then(fp => {
            fp.get().then(result => {
                const visitorId = result.visitorId;
                console.log(visitorId)
                document.getElementById('id_fingerprint').value = visitorId;
            });
        });
    }
</script>
<script
    async
    src="//cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js"
    onload="initFingerprintJS()"
></script>

menu_app/templates/bases/footer.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'menu_app/css/footer_style.css' %}">
<div class="footer-block">
    <address>
        <p>
            &copy 2020-2021. Первая подгруппа четвёртой группы онлайн-отделения ШП
            (<a href="https://informatics.ru/">informatics.ru</a>)
        </p>
        <p>Gitlab-репозиторий проекта -
            <a href="https://gitlab.informatics.ru/2020-2021/online/s101/group-04/simple-votings-1">
                gitlab.informatics.ru/2020-2021/online/s101/group-04/simple-votings-1
            </a>
        </p>
    </address>
</div>

menu_app/templates/bases/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% if field.errors %}
            <div class="small-block">
                <h3>{{ field.label }}</h3>
                <div class="list-elem">
                    <ul>
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    {% if form.non_field_errors %}
        <div class="small-block">
            <h3>Другое</h3>
            <div class="list-elem">
                <ul>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
{% endif %}

menu_app/templates/bases/menu.html
{% load static %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'css/border_animation.css' %}">-->
<link rel="stylesheet" type="text/css" href="{% static 'css/btn_style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'menu_app/css/menu_style.css' %}">
<nav class="menu">
    <a href="{% url 'menu' %}" class="logo">
        <div class="logo__name">SV-1</div>
        <div class="logo__online">Online-4</div>
    </a>
    {% for item in menu %}
        <a href="{{ item.url }}" class="anim-btn horizontal-border">
            {{ item.label }}
        </a>
    {% endfor %}
    {% if request.user.is_authenticated %}
        <div class="login-profile-block">
            {% for item in profile_menu %}
                <a href="{{ item.url }}" class="anim-btn horizontal-border">
                    {{ item.label }}
                </a>
            {% endfor %}
        </div>
    {% else %}
        <div class="login-profile-block">
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {{ login_form.username }}
                {{ login_form.password }}
                <input class="small-btn green" type="submit" value="Войти">
            </form>
            <button class="small-btn yellow" id="reg_btn">Регистрация</button>
        </div>
    {% endif %}
</nav>
{% if not request.user.is_authenticated %}
    <div class="block hidden-top" id="reg_block">
        <h2>Регистрация</h2>
        <form action="{% url 'django_registration_register' %}" method="post">
            {% csrf_token %}
            {{ reg_form.username }}
            {{ reg_form.email }}
            {{ reg_form.password1 }}
            {{ reg_form.password2 }}
            <input type="submit" value="Зарегистрироваться" class="medium-btn green">
        </form>
    </div>
{% endif %}
<div id="window_bg" class="window-around-bg"></div>
<script>
    let toggle_reg_form = function(e) {
        reg_block.classList.toggle('hidden-top');
        bg.classList.toggle('active-bg')
    }

    reg_btn = document.getElementById('reg_btn');
    reg_block = document.getElementById('reg_block');
    bg = document.getElementById('window_bg');
    reg_btn.addEventListener('click', toggle_reg_form);
    bg.addEventListener('click', toggle_reg_form);
</script>

menu_app/templates/bases/radio_animation.html
<svg width="20px" height="20px" viewBox="0 0 20 20">
    <circle cx="10" cy="10" r="9"></circle>
    <path d="M10,7 C8.34314575,7 7,8.34314575 7,10 C7,11.6568542 8.34314575,13 10,13 C11.6568542,13 13,11.6568542 13,10 C13,8.34314575 11.6568542,7 10,7 Z" class="inner"></path>
    <path d="M10,1 L10,1 L10,1 C14.9705627,1 19,5.02943725 19,10 L19,10 L19,10 C19,14.9705627 14.9705627,19 10,19 L10,19 L10,19 C5.02943725,19 1,14.9705627 1,10 L1,10 L1,10 C1,5.02943725 5.02943725,1 10,1 L10,1 Z" class="outer"></path>
</svg>