django_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

import menu_app.views as menu

import profile_app.views as profile
from django_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', menu.IndexView.as_view(), name='menu'),

    path('vote/', include('vote_app.urls')),

    path('profile/view/<int:profile_id>/', profile.ProfilePageView.as_view(), name='profile_view'),

    path('account/', include('profile_app.urls')),

    path('moderation/', include('moderation_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moderation_app/urls.py
from django.urls import path

import moderation_app.views as moder_main
import moderation_app.view_report_subclasses as report
import moderation_app.view_request_subclasses as change_request


urlpatterns = [
    path('send/', report.SendReportView.as_view(), name='moder_report_send'),
    path('send/success/', report.SendReportSuccessView.as_view(), name='moder_report_send_success'),
    path('manage/', moder_main.ModerationPanelView.as_view(), name='moder_manage'),
    path('manage/reports/list/', report.ReportsListView.as_view(), name='moder_reports_list'),
    path('manage/reports/submit/<int:report_id>/', report.ReportSubmitView.as_view(),
         name='moder_report_submit'),
    path('manage/reports/reject/<int:report_id>/', report.ReportRejectView.as_view(),
         name='moder_report_reject'),
    path('manage/change_request/list/', change_request.ChangeRequestsListView.as_view(),
         name='moder_change_request_list'),
    path('manage/change_request/<int:request_id>/', change_request.ChangeRequestView.as_view(),
         name='moder_change_request_form'),
    path('manage/change_request/submit/<int:request_id>/', change_request.ChangeRequestSubmitView.as_view(),
         name='moder_change_request_submit'),
    path('manage/change_request/reject/<int:request_id>/', change_request.ChangeRequestRejectView.as_view(),
         name='moder_change_request_reject'),
]

vote_app/urls.py
from django.urls import path
import vote_app.views as vote_main
import vote_app.view_vote_config_subclasses as vote_config
import vote_app.view_vote_one_subclasses as vote_one


urlpatterns = [
    path('list/', vote_main.VoteListPageView.as_view(), name='vote_list'),
    path('create/', vote_config.CreateVotingView.as_view(), name='vote_create'),
    path('edit/<int:voting_id>/', vote_config.EditVotingView.as_view(), name='vote_edit'),
    path('delete/<int:voting_id>/', vote_one.DeleteVotingView.as_view(), name='vote_delete'),
    path('view/<int:voting_id>/', vote_one.VotingView.as_view(), name='vote_view'),
]

moderation_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from vote_app.models import Votings


class Reports(models.Model):
    VOTING_REPORT = 0
    ERROR_MESSAGE = 1
    THEMES = [
        (VOTING_REPORT, 'Жалоба на голосование'),
        (ERROR_MESSAGE, 'Сообщение об ошибке'),
    ]

    IN_PROCESS = 0
    SUBMITTED = 1
    REJECTED = 2
    STATUSES = [
        (IN_PROCESS, 'Обрабатывается'),
        (SUBMITTED, 'Решена'),
        (REJECTED, 'Отклонена')
    ]

    author = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True)
    theme = models.IntegerField(choices=THEMES, default=0)
    element = models.IntegerField(null=True, blank=True)  # id модели, соответствующей теме жалобы
    content = models.TextField()
    status = models.IntegerField(choices=STATUSES, default=0)
    create_date = models.DateTimeField(auto_now_add=True)
    close_date = models.DateTimeField(null=True, blank=True)

    def is_url_need(self):
        return self.theme == 0

    def get_object_url_from_report(self):
        if not self.is_url_need():
            return ''
        if self.theme == 0 and self.element is not None:
            return reverse_lazy('vote_view', args=(self.element,))
        else:
            return ''

    def get_humanity_theme_name(self):
        for THEME in self.THEMES:
            if THEME[0] == self.theme:
                return THEME[1]
        return 'Ошибочная тема'

    def get_humanity_status_name(self):
        for STATUS in self.STATUSES:
            if STATUS[0] == self.status:
                return STATUS[1]
        return 'Ошибочный статус'

    @staticmethod
    def get_absolute_url():
        return reverse_lazy('moder_report_send')

    def __str__(self):
        return f'{self.author.username} - {self.get_humanity_theme_name()}'


class VoteChangeRequest(models.Model):
    voting = models.ForeignKey(to=Votings, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    image = models.ImageField(upload_to='voting_images/', blank=True, null=True)  # FileField()
    description = models.TextField()
    end_date = models.DateTimeField(blank=True, null=True)

    ALL = 0
    VOTED = 1
    SEE_WHO_CHOICES = [
        (ALL, 'Всем'),
        (VOTED, 'Проголосовавшим'),
    ]
    result_see_who = models.IntegerField(null=True, default=0, choices=SEE_WHO_CHOICES)

    ANYTIME = 0
    BY_TIMER = 1
    SEE_WHEN_CHOICES = [
        (ANYTIME, 'В любое время'),
        (BY_TIMER, 'После окончания'),
    ]
    result_see_when = models.IntegerField(null=True, default=0, choices=SEE_WHEN_CHOICES)

    variants_count = models.IntegerField(default=2)
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()

    def get_absolute_url(self):
        return reverse_lazy('vote_view', args=(self.pk,))

    def get_result_see_who_name(self):
        for note in self.SEE_WHO_CHOICES:
            if note[0] == self.result_see_who:
                return note[1]

    def get_result_see_when_name(self):
        for note in self.SEE_WHEN_CHOICES:
            if note[0] == self.result_see_when:
                return note[1]

    def get_img_url(self):
        try:
            return self.image.url
        except ValueError:
            return ''

    def __str__(self):
        return self.voting


class VoteVariantsChangeRequest(models.Model):
    voting_request = models.ForeignKey(to=VoteChangeRequest, on_delete=models.CASCADE)
    serial_number = models.IntegerField()
    description = models.TextField()

    def get_absolute_url(self):
        return reverse_lazy('vote_view', args=(self.voting_request.pk,))

    def __str__(self):
        return self.description

moderation_app/forms.py
from django import forms

from moderation_app.models import Reports


class CommentForm(forms.Form):
    comment = forms.CharField(
        label='Комментарий',
        widget=forms.Textarea(attrs={
            'placeholder': 'Напишите комментарий',
            'class': 'input wide',
        }))


class EditRequestForm(forms.Form):
    comment = forms.CharField(required=False,
                              label='Комментарий к решению (необязательно)',
                              widget=forms.Textarea(attrs={
                                    'placeholder': 'Комментарий к решению (необязательно)',
                                    'class': 'input wide',
                                }))
    reset_votes = forms.BooleanField(required=False,
                                     label='Обнулить голоса (только при одобрении)')


class ModeledReportCreateForm(forms.ModelForm):
    class Meta:
        model = Reports
        fields = [
            'author', 'element', 'theme', 'content',
        ]
        labels = {
            'theme': 'Тема жалобы',
            'content': 'Содержание жалобы',
            'element': 'Объект жалобы, для заполнения нужно нажимать на кнопку жалобы около объектов',
        }
        widgets = {
            'theme': forms.Select(attrs={
                'class': 'input wide',
            }),
            'content': forms.Textarea(attrs={
                'placeholder': 'Содержание жалобы (подробное описание значительно повышает шанс на адекватный ответ)',
                'class': 'input wide',
            }),
            'author': forms.TextInput(attrs={
                'type': 'hidden',
                'id': 'author',
            }),
            'element': forms.NumberInput(attrs={
                'placeholder': 'Пусто',
                'readonly': True,
                'disabled': True,
                'class': 'input wide',
                'id': 'element',
            }),
        }

moderation_app/views.py
from menu_app.view_subclasses import TemplateViewWithMenu
from moderation_app.models import Reports, VoteChangeRequest


class ModerationPanelView(TemplateViewWithMenu):
    template_name = 'moderation_main.html'

    def get_context_data(self, **kwargs):
        context = super(ModerationPanelView, self).get_context_data(**kwargs)
        context.update({
            'reports': {
                'all': len(Reports.objects.all()),
                'submitted': len(Reports.objects.filter(status=Reports.SUBMITTED)),
                'rejected': len(Reports.objects.filter(status=Reports.REJECTED)),
                'processed': len(Reports.objects.exclude(status=Reports.IN_PROCESS)),
            },
            'change_request': {
                'all': len(VoteChangeRequest.objects.all()),
            },
        })
        return context

moderation_app/templates/change_requests/change_request_one.html
{% extends 'moder_base.html' %}
{% load static %}

{% block head %}
    <title>Запросы на изменения</title>
    <style>
        .list-elem * {
            margin: 5px;
        }
    </style>
{% endblock %}


{% block for_moder %}
    <div class="block">
        <h1>Запрос номер {{ request_id }}</h1>
        <div class="medium-block horizontal-centering grey-2">
            <div class="list-elem wide grey-3">
                <h2>{{ object.voting.title }}</h2>
                <p class="meta-data">{{ object.date }}</p>
                <p class="meta-data">
                    {{ object.voting.author }}
                    <a class="small-btn blue fas fa-arrow-right" href="{% url 'profile_view' object.voting.author.id %}"></a>
                </p>
            </div>
            <h3 class="wide">Комментарий автора</h3>
            <p class="wide">{{ object.comment }}</p>
        </div>
        <div class="medium-block horizontal-centering grey-2">
            <h2>Список изменений</h2>
            {% for change in changes %}
                <div class="list-elem wide grey-3">
                    <div class="horizontal-centring">
                        <h4>{{ change.name }}</h4>
                        {% if change.name != image_label %}
                            <ul>
                                <li>Было: {{ change.old }}</li>
                                <li>Стало: {{ change.new }}</li>
                            </ul>
                        {% else %}
                            <div class="horizontal-centering">
                                <div class="small-block medium">
                                    <h3>Было:</h3>
                                    {% if object.voting.get_img_url != '' %}
                                        <img src="{{ object.voting.get_img_url }}" class="card-img">
                                    {% else %}
                                        <h4 class="center">Пусто</h4>
                                    {% endif %}
                                </div>
                                <div class="small-block medium">
                                    <h3>Стало:</h3>
                                    {% if object.get_img_url != '' %}
                                        <img src="{{ object.get_img_url }}" class="card-img">
                                    {% else %}
                                        <h4 class="center">Пусто</h4>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="medium-block horizontal-centering grey-2">
            <h2 class="wide">Действия</h2>
            <div class="horizontal-centering wide">
                <a type="submit" href="{% url 'moder_change_request_submit' request_id %}" class="big-btn green">Одобрить</a>
                <a type="submit" href="{% url 'moder_change_request_reject' request_id %}" class="big-btn red">Отклонить</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block moder_bottom %}
    <a href="{% url 'moder_manage' %}" class="big-btn blue">Панель модератора</a>
    <a href="{% url 'moder_change_request_list' %}" class="big-btn green">Список запросов на изменения</a>
{% endblock %}

moderation_app/templates/change_requests/change_request_reject.html
{% extends 'moder_base.html' %}

{% block head %}
    <title>Одобрение жалобы</title>
{% endblock %}

{% block for_moder %}
    <h1>Запрос почти отклонён!</h1>
    <h2>Перед одобрением выберите дополнительны действия</h2>
    <div class="block">
        <form method="post" action="{% url 'moder_change_request_reject' request_id %}" class="horizontal-centering">
            {% csrf_token %}
            {{ form.comment }}
            <input type="submit" value="Отклонить запрос" class="big-btn red">
        </form>
    </div>
{% endblock %}

moderation_app/templates/change_requests/change_request_submit.html
{% extends 'moder_base.html' %}

{% block head %}
    <title>Одобрение жалобы</title>
{% endblock %}

{% block for_moder %}
    <h1>Запрос почти одобрен!</h1>
    <h2>Перед одобрением ыберите дополнительны действия</h2>
    <div class="block">
        <form method="post" action="{% url 'moder_change_request_submit' request_id %}" class="horizontal-centering">
            {% csrf_token %}
            {{ form.comment }}
            <div class="input-block vertical-centering medium">
                <div class="checkbox path">
                    {{ form.reset_votes }}
                    {% include 'bases/checkbox_animation.html' %}
                </div>
                <label class="wide" for="id_reset_votes">
                {{ form.reset_votes.label }}
                </label>
            </div>
            <input type="submit" value="Одобрить запрос" class="big-btn green">
        </form>
    </div>
{% endblock %}

moderation_app/templates/change_requests/change_requests_list.html
{% extends 'moder_base.html' %}
{% load static %}

{% block head %}
    <title>Запросы на изменения</title>
    <style>
        .list-elem * {
            margin: 5px;
        }
    </style>
{% endblock %}


{% block for_moder %}
    <h1>Список запросов на изменения</h1>
    <div class="horizontal-centering">
        <div class="block wide">
            {% if change_requests|length == 0 %}
                <h4 class="center">Список пуст</h4>
            {% else %}
                {% for request in change_requests %}
                    <div class="list-elem">
                        <h4>{{ request.title }}</h4>
                        <span class="meta-data">{{ request.date }}</span>
                        <div>
                            <a href="{{ request.form_url }}" class="medium-btn yellow">Просмотр изменений</a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block moder_bottom %}
    <a href="{% url 'moder_manage' %}" class="big-btn blue">Панель модератора</a>
{% endblock %}